export * from './adminController.service';
import { AdminControllerService } from './adminController.service';
export * from './articles.service';
import { ArticlesService } from './articles.service';
export * from './authentification.service';
import { AuthentificationService } from './authentification.service';
export * from './categories.service';
import { CategoriesService } from './categories.service';
export * from './clients.service';
import { ClientsService } from './clients.service';
export * from './commandeClients.service';
import { CommandeClientsService } from './commandeClients.service';
export * from './commandeFournisseurs.service';
import { CommandeFournisseursService } from './commandeFournisseurs.service';
export * from './entreprises.service';
import { EntreprisesService } from './entreprises.service';
export * from './fournisseurs.service';
import { FournisseursService } from './fournisseurs.service';
export * from './management.service';
import { ManagementService } from './management.service';
export * from './sousCategories.service';
import { SousCategoriesService } from './sousCategories.service';
export * from './utilisateurs.service';
import { UtilisateursService } from './utilisateurs.service';
export * from './ventes.service';
import { VentesService } from './ventes.service';
export const APIS = [AdminControllerService, ArticlesService, AuthentificationService, CategoriesService, ClientsService, CommandeClientsService, CommandeFournisseursService, EntreprisesService, FournisseursService, ManagementService, SousCategoriesService, UtilisateursService, VentesService];
