/**
 * OpenApi specification - Ousmane Vincent Dione
 * OpenApi documentation for Stock Management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dioneousmanevincent@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SousCategoryDto } from './sousCategoryDto';


export interface ArticleDto { 
    id?: number;
    codeArticle?: string;
    designation?: string;
    prixUnitaireHt?: number;
    tauxTval?: number;
    prixUnitaireTtc?: number;
    photo?: string;
    idEntreprise?: number;
    sousCategoryDto?: SousCategoryDto;
}

