/**
 * OpenApi specification - Ousmane Vincent Dione
 * OpenApi documentation for Stock Management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dioneousmanevincent@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ArticleStockStatsDto { 
    articleId?: number;
    designation?: string;
    prixUnitaireHt?: number;
    prixUnitaireTtc?: number;
    stockRestant?: number;
    quantiteVendue?: number;
    montantTotal?: number;
    montantTotalAchete?: number;
    benefice?: number;
    marge?: number;
}

