/**
 * OpenApi specification - Ousmane Vincent Dione
 * OpenApi documentation for Stock Management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dioneousmanevincent@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Unite } from './unite';
import { LigneVente } from './ligneVente';
import { SousCategory } from './sousCategory';
import { MvtStk } from './mvtStk';
import { LigneCommandeClient } from './ligneCommandeClient';
import { LigneCommandeFournisseur } from './ligneCommandeFournisseur';
import { ConditionAV } from './conditionAV';


export interface Article { 
    id?: number;
    codeArticle?: string;
    designation?: string;
    prixUnitaireHt?: number;
    tauxTval?: number;
    prixUnitaireTtc?: number;
    photo?: string;
    idEntreprise?: number;
    sousCategory?: SousCategory;
    ligneVentes?: Array<LigneVente>;
    ligneCommandeClients?: Array<LigneCommandeClient>;
    ligneCommandeFournisseurs?: Array<LigneCommandeFournisseur>;
    mvtStks?: Array<MvtStk>;
    conditions?: Array<ConditionAV>;
    unites?: Array<Unite>;
}

