/**
 * OpenApi specification - Ousmane Vincent Dione
 * OpenApi documentation for Stock Management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dioneousmanevincent@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModePayement } from './modePayement';
import { Fournisseur } from './fournisseur';
import { LigneCommandeFournisseur } from './ligneCommandeFournisseur';


export interface CommandeFournisseur { 
    id?: number;
    code?: string;
    dateCommande?: string;
    etatCommande?: CommandeFournisseur.EtatCommandeEnum;
    idEntreprise?: number;
    fournisseur?: Fournisseur;
    ligneCommandeFournisseurs?: Array<LigneCommandeFournisseur>;
    modePayement?: ModePayement;
}
export namespace CommandeFournisseur {
    export type EtatCommandeEnum = 'EN_PREPARATION' | 'VALIDEE' | 'LIVREE';
    export const EtatCommandeEnum = {
        EnPreparation: 'EN_PREPARATION' as EtatCommandeEnum,
        Validee: 'VALIDEE' as EtatCommandeEnum,
        Livree: 'LIVREE' as EtatCommandeEnum
    };
}


