/**
 * OpenApi specification - Ousmane Vincent Dione
 * OpenApi documentation for Stock Management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dioneousmanevincent@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModePayement } from './modePayement';
import { LigneCommandeClient } from './ligneCommandeClient';
import { Client } from './client';


export interface CommandeClient { 
    id?: number;
    code?: string;
    dateCommande?: string;
    etat?: CommandeClient.EtatEnum;
    client?: Client;
    ligneCommandeClients?: Array<LigneCommandeClient>;
    modePayement?: ModePayement;
}
export namespace CommandeClient {
    export type EtatEnum = 'EN_PREPARATION' | 'VALIDEE' | 'LIVREE';
    export const EtatEnum = {
        EnPreparation: 'EN_PREPARATION' as EtatEnum,
        Validee: 'VALIDEE' as EtatEnum,
        Livree: 'LIVREE' as EtatEnum
    };
}


