/**
 * OpenApi specification - Ousmane Vincent Dione
 * OpenApi documentation for Stock Management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dioneousmanevincent@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Critères de recherche
 */
export interface CommandeClientSearchCriteria { 
    code?: string;
    nomClient?: string;
    emailClient?: string;
    numTelClient?: string;
    dateFrom?: string;
    dateTo?: string;
    etat?: string;
    modePayement?: string;
}

