/**
 * OpenApi specification - Ousmane Vincent Dione
 * OpenApi documentation for Stock Management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dioneousmanevincent@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UniteDto } from './uniteDto';
import { ArticleDto } from './articleDto';


export interface ConditionAVDto { 
    id?: number;
    quantity?: number;
    price?: number;
    unite?: UniteDto;
    article?: ArticleDto;
}

