/**
 * OpenApi specification - Ousmane Vincent Dione
 * OpenApi documentation for Stock Management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dioneousmanevincent@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Article } from './article';
import { CommandeFournisseur } from './commandeFournisseur';


export interface LigneCommandeFournisseur { 
    id?: number;
    article?: Article;
    idEntreprise?: number;
    unite?: string;
    quantite?: number;
    prixUnitaire?: number;
    commandeFournisseur?: CommandeFournisseur;
}

