/**
 * OpenApi specification - Ousmane Vincent Dione
 * OpenApi documentation for Stock Management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dioneousmanevincent@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Ventes } from './ventes';
import { Article } from './article';


export interface LigneVente { 
    id?: number;
    vente?: Ventes;
    quantite?: number;
    prixUnitaire?: number;
    idEntreprise?: number;
    unite?: string;
    article?: Article;
}

