/**
 * OpenApi specification - Ousmane Vincent Dione
 * OpenApi documentation for Stock Management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dioneousmanevincent@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Ventes } from './ventes';
import { CommandeClient } from './commandeClient';
import { CommandeFournisseur } from './commandeFournisseur';


export interface ModePayement { 
    id?: number;
    code?: string;
    designation?: string;
    ventes?: Array<Ventes>;
    commandeClients?: Array<CommandeClient>;
    commandeFournisseurs?: Array<CommandeFournisseur>;
}

