/**
 * OpenApi specification - Ousmane Vincent Dione
 * OpenApi documentation for Stock Management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dioneousmanevincent@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterRequest { 
    nom?: string;
    prenom?: string;
    username?: string;
    email?: string;
    password?: string;
    role?: RegisterRequest.RoleEnum;
}
export namespace RegisterRequest {
    export type RoleEnum = 'USER' | 'ADMIN' | 'MANAGER';
    export const RoleEnum = {
        User: 'USER' as RoleEnum,
        Admin: 'ADMIN' as RoleEnum,
        Manager: 'MANAGER' as RoleEnum
    };
}


