/**
 * OpenApi specification - Ousmane Vincent Dione
 * OpenApi documentation for Stock Management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dioneousmanevincent@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Utilisateur } from './utilisateur';


export interface Token { 
    id?: number;
    token?: string;
    tokenType?: Token.TokenTypeEnum;
    revoked?: boolean;
    expired?: boolean;
    utilisateur?: Utilisateur;
}
export namespace Token {
    export type TokenTypeEnum = 'BEARER';
    export const TokenTypeEnum = {
        Bearer: 'BEARER' as TokenTypeEnum
    };
}


