/**
 * OpenApi specification - Ousmane Vincent Dione
 * OpenApi documentation for Stock Management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dioneousmanevincent@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntrepriseDto } from './entrepriseDto';
import { AdresseDto } from './adresseDto';


export interface UtilisateurDto { 
    id?: number;
    username?: string;
    password?: string;
    email?: string;
    nom?: string;
    prenom?: string;
    dateDeNaissance?: string;
    entrepriseDto?: EntrepriseDto;
    role?: UtilisateurDto.RoleEnum;
    adresse?: AdresseDto;
}
export namespace UtilisateurDto {
    export type RoleEnum = 'USER' | 'SUPER_ADMIN' | 'LIVREUR' | 'ADMIN' | 'MANAGER';
    export const RoleEnum = {
        User: 'USER' as RoleEnum,
        SuperAdmin: 'SUPER_ADMIN' as RoleEnum,
        Livreur: 'LIVREUR' as RoleEnum,
        Admin: 'ADMIN' as RoleEnum,
        Manager: 'MANAGER' as RoleEnum
    };
}


