/**
 * OpenApi specification - Ousmane Vincent Dione
 * OpenApi documentation for Stock Management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dioneousmanevincent@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Adresse } from './adresse';
import { Entreprise } from './entreprise';
import { GrantedAuthority } from './grantedAuthority';
import { Token } from './token';
import { Livraison } from './livraison';


export interface Utilisateur { 
    id?: number;
    username?: string;
    password?: string;
    email?: string;
    nom?: string;
    prenom?: string;
    dateDeNaissance?: string;
    adresse?: Adresse;
    entreprise?: Entreprise;
    role?: Utilisateur.RoleEnum;
    tokens?: Array<Token>;
    livraisons?: Array<Livraison>;
    enabled?: boolean;
    authorities?: Array<GrantedAuthority>;
    accountNonExpired?: boolean;
    credentialsNonExpired?: boolean;
    accountNonLocked?: boolean;
}
export namespace Utilisateur {
    export type RoleEnum = 'USER' | 'LIVREUR' | 'ADMIN' | 'MANAGER';
    export const RoleEnum = {
        User: 'USER' as RoleEnum,
        Livreur: 'LIVREUR' as RoleEnum,
        Admin: 'ADMIN' as RoleEnum,
        Manager: 'MANAGER' as RoleEnum
    };
}


