/**
 * OpenApi specification - Ousmane Vincent Dione
 * OpenApi documentation for Stock Management
 *
 * The version of the OpenAPI document: 1.0
 * Contact: dioneousmanevincent@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VenteSearchCriteria { 
    nomClient?: string;
    prenomClient?: string;
    codeVente?: string;
    numeroClient?: string;
    adresse?: string;
    dateFrom?: string;
    dateTo?: string;
    page?: number;
    size?: number;
    sortBy?: string;
    sortDirection?: VenteSearchCriteria.SortDirectionEnum;
}
export namespace VenteSearchCriteria {
    export type SortDirectionEnum = 'ASC' | 'DESC';
    export const SortDirectionEnum = {
        Asc: 'ASC' as SortDirectionEnum,
        Desc: 'DESC' as SortDirectionEnum
    };
}


